Feature/split main
Lee-Park-Bae-Project/KAKIOTALK pull request #109
Opened 2020-06-11 11:17 UTC by brillante06

deploy to github page and google app engine

2020-06-12 06:35 UTC, Junow requested changes

2020-06-12 06:35 UTC, Junow commented on packages/server/package.json
> +    "test": "_NODE_ENV=test npm run migrate:reset && _NODE_ENV=test npm run migrate && _NODE_ENV=test npm run seed && node_modules/.bin/jest --detectOpenHandles --watchAll",
_NODE_ENV 로 바꾼 이유는 뭔가요? 바꿀거라면 test script 를 실행할 때 NODE_ENV 를 읽는 부분이 모두 동시에 수정이 되어야할 것으로 보입니다.

2020-06-12 06:35 UTC, Junow commented on packages/server/src/seeders/20200504111441-seed-users.js
> +    ),
린트 규칙을 수정하셨나요?
![image](https://user-images.githubusercontent.com/32632221/84472040-8a77e400-acc1-11ea-8170-7ebed00bb5df.png)

저같은 경우 이런 에러가 나는데 line-break style 을 끄셔서 그런건가요

2020-06-12 06:35 UTC, Junow commented on packages/server/package.json
> +    "start": "node dist/bin/www.js",
start 를 배포에서 쓰기로 했던거 같은데 그러면 로컬에서 개발할때는 어떤 명령어를 써야하나요?

2020-06-12 07:06 UTC, brillante06 commented on packages/server/package.json
> +    "test": "_NODE_ENV=test npm run migrate:reset && _NODE_ENV=test npm run migrate && _NODE_ENV=test npm run seed && node_modules/.bin/jest --detectOpenHandles --watchAll",
테스트를 위해 잠시 바꿨습니다.
NODE_ENV로 다시 수정하겠습니다.

2020-06-12 07:07 UTC, brillante06 commented on packages/server/src/seeders/20200504111441-seed-users.js
> +    ),
네 line-break style을 꺼놨습니다.

2020-06-12 07:08 UTC, brillante06 commented on packages/server/package.json
> +    "start": "node dist/bin/www.js",
dev_start로 하면 좋을 것 같은데 어떻게 생각하시나요

2020-06-12 15:16 UTC, Junow commented on packages/server/src/seeders/20200504111441-seed-users.js
> +    ),
근데 규칙을 아예 꺼버리면 전체 소스코드에 변경이 일어나지 않을까요?

2020-06-12 15:17 UTC, Junow commented on packages/server/package.json
> +    "start": "node dist/bin/www.js",
치기 귀찮으니까 dev 정도로 하시죠

2020-06-12 16:24 UTC, Junow commented on packages/client/src/components/GoogleSignin/index.tsx
> +const loginURL = configs.NODE_ENV_VAR === 'production' ? configs.LOGIN_URL_PRODUCT : configs.LOGIN_URL
NODE_ENV_VAR 은 어떤 역할인가요? 기존의 NODE_ENV 랑은 다른건가요?

2020-06-12 16:27 UTC, brillante06 commented on packages/client/src/components/GoogleSignin/index.tsx
> +const loginURL = configs.NODE_ENV_VAR === 'production' ? configs.LOGIN_URL_PRODUCT : configs.LOGIN_URL
클라도 개발용과 배포용 주소를 달리 설정해야 해서 추가해주었습니다.

2020-06-15 13:09 UTC, Junow approved these changes

2020-06-15 13:09 UTC, merged