Feature/tab refactor
Lee-Park-Bae-Project/KAKIOTALK pull request #111
Opened 2020-06-12 19:56 UTC by bbumjun

- tab selector 제거 & 메인 페이지 중첩 라우팅
> main container 가 가져야 하는 불필요한 props를 최소화 하기 위해 tab selector를 제거했습니다.
친구 탭과 채팅목록 탭은 main component에서 중첩 라우팅을 통해 연결됩니다. 자연스럽게 채팅방에서의 history.goback() 의 이슈도 해결되었습니다.
이 과정에서 main url 을 `/` 에서 `/main`으로 변경했습니다.
또한 tab selector의 boolean 값을 통해 navigation bar 의 버튼을 filled 하던 방식대신 history의 pathname을 사용했습니다.
- main container에서 할 필요 없는 기능은 각자 자리로 이동
> 기존에 친구추가 , 로그아웃 기능은 메인 컨테이너에 있을 필요가 없다고 생각해 각각 친구추가 탭, 로그아웃 탭 컴포넌트 안에서 동작하도록 수정했습니다.
- 로딩 컴포넌트 생성 / 메인 로딩에 적용

2020-06-14 14:29 UTC, Junow requested changes
수고하셨습니다.

2020-06-14 14:29 UTC, Junow commented on packages/client/src/components/Loader/index.tsx
> +const Loader: FC = () => (
잘쓰겠습니다 😄

2020-06-14 14:29 UTC, Junow commented on packages/client/src/components/NavigationBar/AddFriendTab/index.tsx
> +  const dialogRef = React.createRef<HTMLDivElement>()
createRef 를 사용중이셔서 useRef() 와 createRef() 의 차이점이 궁금해져서 알아보았습니다.

https://hyeok999.github.io/2020/01/07/react-study-14/#a5

여기서 설명하기를 createRef() 는 상태가 바뀔때 rerendering 이 일어나는 것으로 설명해주는데요. Dialog component에서는 createRef() 생성된 reference 가 rerendering 되는 것이 의도된 동작인가요? 간단히 생각해보니 친구추가를 할때 친구 email 을 입력할때마다 Dialog 컴포넌트가 rerendering 이 되지 않을까 그럼 그때마다 dialogRef 가 불필요하게 재생성되지 않을까 하는 생각이 드네요. 직접 확인해보진 않았지만 짚고 넘어가면 좋은 문제인 것 같습니다.

2020-06-14 14:29 UTC, Junow commented on packages/client/src/components/NavigationBar/ChatTab/index.tsx
>      }
위아래 코드가 중복되는게 보이네요 리팩토링한다면 이런 형식으로는 안될까요?
```typescript
<Icon icon={isRouted ? 'ChatFilled' : 'Chat'} color={color.WHITE} size={size}/>
```

2020-06-14 14:29 UTC, Junow commented on packages/client/src/components/NavigationBar/LogoutTab/index.tsx
> +  }
단순히 클릭 이라는 onClick 이라는 네이밍보다는 handlePopupClose 같은 이름을 사용한다면 함수의 목적을 더 이해하기 쉬울것 같아요
https://blog.sonim1.com/220

2020-06-14 14:29 UTC, Junow commented on packages/client/src/pages/main/index.tsx
> +}
보기좋은 코드네여 😸

2020-06-14 14:29 UTC, Junow commented on packages/client/src/system/Room/index.tsx
> +const Room: React.FC<RouteComponentProps> = ({ history }) => {
이 컴포넌트는 방목록을 나타내는 컴포넌트죠? 제가 만드는 ChatRoom 하고 헷갈리네요 이 부분은 네이밍을 다시 해봐야겠습니다.

2020-06-14 14:29 UTC, Junow commented on packages/client/src/system/Profile/index.tsx
>    const onTouch = (e: React.TouchEvent) => {
터치이벤트는 스크롤 이벤트처럼 터치입력이 들어왔을때 연속적으로 이벤트가 발생하나요?

2020-06-15 06:35 UTC, bbumjun commented on packages/client/src/components/NavigationBar/AddFriendTab/index.tsx
> +  const dialogRef = React.createRef<HTMLDivElement>()
좋은 자료 감사합니다.
무심코 createRef를 사용하고 있엇는데 저도 궁금해져서 자료를 더 찾아봤습니다.
[https://blog.bitsrc.io/react-useref-and-react-createref-the-difference-afedb9877d0f](url)
class component에서는 createRef를, functional component에서는 useRef를 사용해야 한다고하네요. 말씀하신대로 functional component에서 useRef를 사용하면 불필요한 re-rendering 때문에 성능저하뿐 아니라 컴포넌트가 계속 초기화되서 제대로된 동작을 할수 없다고 하네요!

2020-06-15 06:36 UTC, bbumjun commented on packages/client/src/components/NavigationBar/ChatTab/index.tsx
>      }
엇 그부분은 신경쓰지 못했네요 수정하겠습니다

2020-06-15 06:37 UTC, bbumjun commented on packages/client/src/components/NavigationBar/LogoutTab/index.tsx
> +  }
넵 네이밍에 좀더 신경을 써야겠네요

2020-06-15 06:39 UTC, bbumjun commented on packages/client/src/system/Room/index.tsx
> +const Room: React.FC<RouteComponentProps> = ({ history }) => {
저도 이번에 리팩토링할때 많이 헷갈리더라구요.

2020-06-15 06:43 UTC, bbumjun commented on packages/client/src/system/Profile/index.tsx
>    const onTouch = (e: React.TouchEvent) => {
스크롤이벤트를 사용해보지는 않았지만 모바일 기기에서의 터치에 반응해 연속적인 이벤트가 발생하더라구요.

2020-06-15 08:06 UTC, Junow commented on packages/client/src/components/NavigationBar/AddFriendTab/index.tsx
> +  const dialogRef = React.createRef<HTMLDivElement>()
올려주신 자료해석이 잘 안되서 공식문서를 보고 있습니다. [공식문서](https://ko.reactjs.org/docs/refs-and-the-dom.html#refs-and-function-components)에서 설명하는 글중에 `함수 컴포넌트는 인스턴스가 없기 때문에 함수 컴포넌트에 ref 어트리뷰트를 사용할 수 없습니다.` 라는 설명이 있는데요.
저희가 `UserCard` component 에서 사용하는 `profileRef` 가 `ref` attribute 로 바로 쓰이는게 아니라 아슬아슬하게 에러에 걸리지 않고 있는 느낌이네요 이번 기회에 제대로 공부하고 사용해야겠네요 🙈

2020-06-15 08:07 UTC, Junow commented on packages/client/src/system/Profile/index.tsx
>    const onTouch = (e: React.TouchEvent) => {
드르르륵 연속으로 발생하는 이벤트를 모두 감지할 필요가 없다면 throttling 을 적용해는게 어떨까요

2020-06-15 11:03 UTC, bbumjun commented on packages/client/src/system/Profile/index.tsx
>    const onTouch = (e: React.TouchEvent) => {
의견 감사합니다.
공식문서와 아래 블로그를 참고해서 동작방식을 바꿔봤습니다.
[https://hyunseob.github.io/2018/06/24/debounce-react-synthetic-event](url)

기존의 touchStart 와 touchEnd 핸들러는 한번씩만 실행되기 때문에 수정하지 않았고
touchMove 핸들러에서 이벤트를 감지하는 부분과 state를 변경하는 두 핸들러로 분리해서 state를 변경하는 핸들러는 50ms 마다 실행되도록 throttle을 적용했습니다.

2020-06-15 11:10 UTC, bbumjun commented on packages/client/src/components/NavigationBar/AddFriendTab/index.tsx
> +  const dialogRef = React.createRef<HTMLDivElement>()
저도 그것에 대해서 공식문서에서 읽어보았는데,
>함수 컴포넌트는 인스턴스가 없기 때문에 함수 컴포넌트에 ref 어트리뷰트를 사용할 수 없습니다.
함수 컴포넌트에 ref를 사용할 수 있도록 하려면, forwardRef (높은 확률로 useImperativeHandle와 함께)를 사용하거나 클래스 컴포넌트로 변경할 수 있습니다.
다만, DOM 엘리먼트나 클래스 컴포넌트의 인스턴스에 접근하기 위해 ref 어트리뷰트를 함수 컴포넌트에서 사용하는 것은 됩니다.

라고 하네요.
그래서 저는 부득이하게 dom 에 접근해야 할 경우가 있을 때에만 ref를 dom element에 부착해서 사용하고 있긴합니다.

2020-06-16 01:10 UTC, Junow approved these changes

2020-06-16 01:10 UTC, merged