Feature/tab refactor
Lee-Park-Bae-Project/KAKIOTALK pull request #113
Opened 2020-06-16 07:27 UTC by bbumjun

어제 진행된 머지 이후 빠뜨린 부분이나 수정되어야 할 사항이 몇가지 있어서 다시 풀리퀘 올렸습니다.

- server의 start / deploy script 일부를 수정했습니다.
- server 에서 불필요한 docker-compose 파일을 삭제했습니다.
- login 이후에 push 되는 main url 을 업데이트 했습니다.
- profile touch event에 throttle 적용 이후 slide down 할 경우 가끔씩 버벅거리는 이슈를 해결 했습니다.

2020-06-16 08:46 UTC, Junow requested changes

2020-06-16 08:46 UTC, Junow commented on packages/client/src/components/GoogleSignin/index.tsx
> +        history.push(`${url.main}/friend-list`)
누구는 상수화가 되어있고 누구는 안되있는건 이상한데요?
url.main.friendList 같은건 어떠세요

2020-06-16 08:46 UTC, Junow commented on packages/client/src/system/Profile/index.tsx
> +  ThrottledhandleTouch = throttle(ThrottledhandleTouch, 5)
5 면 5ms 인가요? 스로틀을 걸기엔 너무 짧은 텀이 아닐까요? 아니면 기능상의 이슈가 있나요?

2020-06-16 16:46 UTC, bbumjun commented on packages/client/src/components/GoogleSignin/index.tsx
> +        history.push(`${url.main}/friend-list`)
넵 반영하겠습니다

2020-06-16 16:49 UTC, bbumjun commented on packages/client/src/system/Profile/index.tsx
> +  ThrottledhandleTouch = throttle(ThrottledhandleTouch, 5)
텀이 길어질 경우 프로필을 슬라이드하는 모션이 매끄럽지 못한 이슈가 있었습니다.
그렇다해도 5ms는 너무 throttle이 무색해지는 값인것 같네요.. 좀더 손 보겠습니다

2020-06-17 13:26 UTC, Junow approved these changes

2020-06-17 13:26 UTC, merged