Feature/mobile refactor
Lee-Park-Bae-Project/KAKIOTALK pull request #115
Opened 2020-06-22 06:26 UTC by bbumjun

배포된 앱에서 발견된 몇가지 문제를 수정했습니다.
- 네비게이션 바에서 채팅목록 버튼을 클릭했을 때 라우팅이 제대로 되지 않는 문제를 고쳤습니다.
- 모바일 화면에서 프로필을 클릭 후 슬라이드했을 때 새로고침이 함께 되는 문제가 있었습니다. 좋은 방법인지는 모르겠지만 스와이프하여 새로고침하는 기능이 굳이 필요없다고 판단하여 모바일에서는 full to refresh 기능을 방지하였습니다.

2020-06-22 16:05 UTC, Junow requested changes

2020-06-22 16:05 UTC, Junow commented on packages/client/src/styles/global.ts
> +    overscroll-behavior-y: contain;
스크롤 관련 css 를 전연 스타일로 넣어주셨는데요 다른 스크롤 영역에서 문제없었나요?

2020-06-22 16:05 UTC, Junow commented on packages/client/src/components/Routes/index.tsx
> +    <Route path={url.main.chatList} component={MainContainer} />
이부분에는 어떤 문제가 있었나요? 기존에는 url.main 에 맞으면 Main 안에서 중첩 라우팅이 되는 형태 아니었나요?

2020-06-23 07:24 UTC, bbumjun commented on packages/client/src/styles/global.ts
> +    overscroll-behavior-y: contain;
[https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y)
저는 여기를 참고했는데요, 모바일 브라우저에서 스크롤 체이닝이나  새로고침 이펙트를 방지하고 싶을 때 사용한다고 합니다. 친구목록을 스크롤이 생길만큼 늘려봤을 때에는 문제 없었습니다.

2020-06-23 07:27 UTC, bbumjun commented on packages/client/src/components/Routes/index.tsx
> +    <Route path={url.main.chatList} component={MainContainer} />
잘못된 방법으로 코드를 수정한 것 같습니다. 다시 푸쉬했는데
main.default 를 '/main'으로 만들고 상위 라우터에서 default를 라우팅하도록하고 
Main에서 friend-list와 chat-list를 라우팅하도록 수정했습니다

2020-07-03 07:56 UTC, Junow approved these changes

2020-07-03 08:07 UTC, merged