Feature/make chat
Lee-Park-Bae-Project/KAKIOTALK pull request #117
Opened 2020-06-27 11:29 UTC by brillante06

request.makeRoom 부분에서 오류가 나는데 어떻게 해결해야할지를 모르겠네요 타입문제인 것 같은데 리뷰 부탁드립니다

2020-06-27 12:10 UTC, Junow requested changes

2020-06-27 12:10 UTC, Junow commented on packages/client/src/modules/sagas/roomSaga.ts
> +    const response: roomIdType = yield call(request.makeRoom, payload)
여기서 에러가 난다는건가요?
일단 payload 의 타입과 request.makeRoom 타입이 맞는지 검사부터 해봐야 할것 같네요

2020-07-04 20:08 UTC, Junow requested changes

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +      onConfirm()
로그 지워주세요

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/SelectedName/index.tsx
> +    }
코드작성 팁인데 if 문 안에는 not 조건을 걸어주는게 가독성에 좋습니다.

```javascript
// Bad
const func = (condition1, condition2, condition3) => {
	if(condition1){
		// logic1
		if(condition2){
			// logic2
			if(condition3){
				// login3
			}
		}
	}
}
// good
const func = (condition1, condition2, condition3) => {
	if(!condition1) return
	// logic1
	if(!condition2) return
	// logic2
	if(!condition3) return
	// logic3
}
```

2020-07-04 20:08 UTC, Junow commented on packages/client/src/containers/ChatRoomStartContainer.tsx
> +  const [selectedUser, setSelectedUser] = useState<InviteUser[]>([])
상태변수 정의, 인터페이스 정의, useEffect 가 퍼져있으니 보기힘드네요 useState 같은건 상단에 몰아 써주세요. 인터페이스는 밖으로 빼시는게 나을것 같아요

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/NavigationBar/index.tsx
> +      <MakeChatTab />
왼쪾 네비에 채팅시작 버튼이 있는건가요?

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +    }
클라이언트에서 로그인 여부를 판단하는건가요? 서버에서 로그인 여부를 판단해서 알려주는 형태아닌가요?

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +  }
interface 정의는 바깥에다 해주는게 이쁠거같아요

2020-07-04 20:08 UTC, Junow commented on packages/client/src/modules/room/action.ts
> +import RoomCardStories from 'components/RoomCard/RoomCard.stories'
얘를 잘못 import 된거 같네요?

stories 는 프로젝트에서 아예 뺴버려야겠습니다. 나중에 날잡고 빼시죠

2020-07-04 20:08 UTC, Junow commented on packages/client/src/pages/main/ChatStart/index.tsx
> +}
이 interface 는 왜 export 되어있나요? 공용으로 쓰이는 interface 인가요?

2020-07-04 20:08 UTC, Junow commented on packages/client/src/pages/main/ChatStart/index.tsx
> +  ` }
K 는 어떤 의미가 있는 변수인가요?
밑에보면 안쓰이는 것 같은데 필요없다면 지워주세요

* as S 로 import 된 스타일은 재사용되는 스타일인가요? 재사용되는 거라면 atom 으로 빼는게 맞는것 같습니다.

나중에 MakeChat css 가 변경되었을떄 side effect 를 예상하기 힘들 것 같아요

2020-07-04 20:08 UTC, Junow commented on packages/client/src/pages/main/ChatStart/index.tsx
> +    {friendList.length > 0 ? (
갑자기 생각났는데 어레이가 truthy 한가를 판별할때 보통 `if(friendList.length)` 라고 줄여쓸 수 있습니다. 검색해봤더니 둘이 미세한 성능차이도 있네요

https://stackoverflow.com/questions/32911424/array-length-vs-array-length-0
https://jsperf.com/test-of-array-length

2020-07-04 20:08 UTC, Junow commented on packages/client/src/pages/main/index.tsx
> +          <Route path='/main/make-chat' component={ChatRoomStartContainer}/>
아예 페이지 이동을 해서 채팅 시작을 하는군요?

차라리 모달로 띄워서 친구목록을 보여주는게 UX 가 좋지 않을까요?

2020-07-04 20:08 UTC, Junow commented on packages/client/src/types/index.ts
> +}
InviteUser interface 는 `packages/client/src/components/NavigationBar/MakeChatTab/index.tsx` 에도 정의되어 있던데 한곳에만 정의해두죠

2020-07-04 20:08 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +      throw httpError.IDK
httpError.IDK 는 제가 예전에 땜빵코드로 넣어둔건데 저도 그렇고 너무 남발되고 있네요 ㅠ 적당한 에러메시지를 만들어야겠습니다.

여기서는 `방정보를 찾을 수 없습니다.` 같은 메시지를 만들 수 있겠네요

2020-07-04 20:08 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +      console.log('error in here?')
로그지워주세요

2020-07-04 20:08 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +export const makeRoom = controllerHelper(async (req, res, next) => {
`controllerHelper` 함수를 쓰셨으면 `try`, `catch`, 문을 사용하지 않으셔도 됩니다.
마지막에 클라이언트에게 응답해줄 데이터만 리턴해도 되요

2020-07-04 20:08 UTC, Junow commented on packages/server/src/routes/v1/chat.route.ts
> +router.get('/makeRoom', makeRoom)
방을 만드는 api endpoint 인가요? 데이터를 생성할때에는 post 가 적당해 보입니다.

2020-07-04 20:08 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +import { QueryTypes } from 'sequelize/types'
`QueryTypes` 는 어떤역할을 하나요?

2020-07-04 20:08 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +    const addRoomParticipants = inviteUser.forEach(async (userList:QueryTypes) => {
`controller` 에는 비즈니스 로직이 담기지 않았으면 좋겠네요 `service` 가 비즈니스 로직을 수행해주는 역할로 존재하는데 `controller` 에 복잡한 로직이 들어가면 들어갈수록 단위테스트는 힘들어지고 유지보수에도 애를 먹을 것같네요. 물론 저희는 테스트 코드를 짜지는 않지만 ㅎ;;

2020-07-04 20:08 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +      const userName = await JSON.parse(userList).name
`user` 의 `uuid`, `name` 을 참조하는데 `JSON.parse` 는 어떤 이유로 쓰이고 있는건가요?

2020-07-04 20:08 UTC, Junow commented on packages/server/src/services/chat.ts
> +  console.log('roomParticipants', userName)
로그지워주세요

2020-07-04 20:08 UTC, Junow commented on packages/server/src/services/chat.ts
> +interface userList{
저희는 보통 `interface` 를 대문자로 시작하죠

2020-07-04 20:08 UTC, Junow commented on packages/server/src/services/chat.ts
> +}:userList, roomId) => {
인자로 객체 두개를 받는것 같은데 그렇게 하신 특별한 이유라도 있나요? 특별한 이유가 없다고 객체하나로 만드는게 좋을것 같습니다.

2020-07-04 20:08 UTC, Junow commented on packages/server/src/services/chat.ts
> +  }
`common/error.ts` 에 `USER_NOT_FOUND` 에러객체 생성함수가 있습니다. 여기에 쓰면 되겠군요

2020-07-04 20:08 UTC, Junow commented on packages/server/src/services/chat.ts
> +  const roomParticipant = await models.RoomParticipants.create({
`roomParticipant` 가 생성되지 않는 경우는 없을까요 밑에 `if(! roomParticipant)` 로 에러처리가 필요해보입니다.

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +  }, [selectedList])
콜백함수안에서 `login` 이 쓰이고 있기 때문에 `deps` 에 넣어주셔야겠습니다.

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +import { Link } from 'react-router-dom'
얘는 안쓰이는것 같네요?

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/MakeChat/styles.ts
> +export const Container = styled.label`
container 가 label 인 이유는 무엇인가요?

2020-07-04 20:08 UTC, Junow commented on packages/client/src/components/MakeChat/index.tsx
> +  uuid?: string
uuid 가 옵셔널이어도 되나요?

2020-07-05 17:07 UTC, brillante06 commented on packages/client/src/components/SelectedName/index.tsx
> +    }
네 감사합니다 참고하겠습니다

2020-07-05 17:07 UTC, brillante06 commented on packages/client/src/components/NavigationBar/index.tsx
> +      <MakeChatTab />
네 채팅 버튼 누르면 팝업창이 뜹니다

2020-07-05 17:08 UTC, brillante06 commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +    }
여기 부분은 현재 수정중에 있습니다 수정이후 다시 피드백 해주세요

2020-07-05 17:09 UTC, brillante06 commented on packages/client/src/pages/main/ChatStart/index.tsx
> +}
안에서만 쓰입니다. export 뺄게요

2020-07-05 17:10 UTC, brillante06 commented on packages/client/src/pages/main/ChatStart/index.tsx
> +  ` }
S와 K를 구별해서 쓰려고 했는데 현재 S는 쓰이지 않기 때문에 빼고 K를 S로 수정하겠습니다

2020-07-05 17:12 UTC, brillante06 commented on packages/client/src/pages/main/index.tsx
> +          <Route path='/main/make-chat' component={ChatRoomStartContainer}/>
모달로 띄워서 친구 목록 보여줍니다!

![image](https://user-images.githubusercontent.com/22672155/86538001-21853400-bf2e-11ea-88c2-12b1f39f08d0.png)

2020-07-05 17:12 UTC, brillante06 commented on packages/server/src/controllers/chat.ts
> +      throw httpError.IDK
새로운 에러메세지를 만들어야겠군요

2020-07-05 17:13 UTC, brillante06 commented on packages/server/src/controllers/chat.ts
> +export const makeRoom = controllerHelper(async (req, res, next) => {
네 수정하겠습니다.

2020-07-05 17:13 UTC, brillante06 commented on packages/server/src/routes/v1/chat.route.ts
> +router.get('/makeRoom', makeRoom)
post로 했을때는 문제가 생겨서 일단 get으로 해놓았습니다. 추후에 바꿀 예정입니다.

2020-07-05 17:14 UTC, brillante06 commented on packages/server/src/controllers/chat.ts
> +import { QueryTypes } from 'sequelize/types'
이 부분도 get과 관련있는 부분으로 추후 없어질 예정입니다.

2020-07-05 17:16 UTC, brillante06 commented on packages/server/src/services/chat.ts
> +interface userList{
그런가요?? 다른 부분 확인해보니 대부분 소문자로 되어 있네요

2020-07-05 17:17 UTC, brillante06 commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +  }, [selectedList])
2개의 useEffect를 써서 해결했습니다.

2020-07-05 17:17 UTC, brillante06 commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +import { Link } from 'react-router-dom'
지우도록 하겠습니다.

2020-07-05 17:18 UTC, brillante06 commented on packages/client/src/components/MakeChat/styles.ts
> +export const Container = styled.label`
컨테이너 자체를 눌렀을때 체크가 되도록 해야했기 때문에 label로 했습니다.

2020-07-05 17:29 UTC, Junow commented
> 그룹채팅방과 1대1채팅을 구현중에 있습니다.
> 
> 현재 그룹채팅방을 팝업으로 띄워 구현하였고 1대1 채팅은 말해주신대로 해쉬기능을 적용할 예정입니다.
> 대화 상대 초대를 할때 아이콘을 클릭하거나 이름을 눌렀을때 추가/삭제를 구현하려고 했는데
> 현재 이름을 눌렀을때 팝업창이 꺼져버리는 오류가 있어서 그것도 같이 해결할 예정입니다.

해시 대상은 어떤 값이고 해시함수는 무엇이고 해싱된 결과값은 무엇이 나오게 만들건가요? 아까 잠깐 생각해보니 사용자 아이디를 키로 해싱을 하면 사용자가 많은 단체 채팅방 같은경우에는 키값이 너무 길어 불가능할 거 같은 느낌인데요.

이 부분은 구현에 들어가기 앞서 팀원들하고 합의를 보셔야 할 것 같습니다.

지금 기록을 보니 이 브랜치에만 한달째 커밋중이신데요. 나중에 머지할거리가 감당이 안되겠죠. 화욜날 회의때 한번 합치고나서 오류 수정 들어가시는게 좋겠습니다.

2020-07-07 07:49 UTC, Junow approved these changes

2020-07-07 08:09 UTC, merged