Feature/1to1chat
Lee-Park-Bae-Project/KAKIOTALK pull request #140
Opened 2020-07-21 02:07 UTC by brillante06

- ChatRoomStartContainer 제거
- 1대1대화 추가
- 대화방 생성 이후 돔 업데이트 추가 예정

2020-07-21 09:59 UTC, Junow requested changes

2020-07-21 09:59 UTC, Junow commented on packages/server/src/routes/v1/chat.route.ts
>  router.post('/:roomUuid', addMessage)
`router.get('/room':roomId')` 와 같이 `router.post('/room')` 이면 좀더 restful 하지 않을까요?
각각 uri 로 방 데이터를 가져온다, 방 데이터를 생성한다로 나누어서 생각할 수 있을 것 같아요

2020-07-21 09:59 UTC, Junow commented on packages/server/src/services/chat.ts
> +import { HTTPVersionNotSupported } from 'http-errors'
`HTTPVersionNotSupported` 는 어떤 에러 처리용인가요?

2020-07-21 09:59 UTC, Junow commented on packages/server/src/services/chat.ts
> +    const participantsList = roomInfo.participants
복수 데이터의 의미로 `participants` 라는 복수형 이름이 있는데 `List` 를 새로 붙인 이유가 따로 있나요?

2020-07-21 09:59 UTC, Junow commented on packages/server/src/services/chat.ts
> +  const friendUuid = user[0].uuid
유저배열을 인자로 받는것 같은데 순서가 뒤바뀌면 다른 의미의 데이터가 생성될 것 같습니다. `structuring` 해서 인자를 받으면 함수내에서의 의미가 명확할 것 같아요. 

```javascript
const makePrivateRoom = async ({
  초대한 사람,
  초대받은 사람
}) => {}
```

아니면 `user` 를 `destructuring` 해서 받을 수도 있겠네요
```javascript
const makePrivateRoom = async(users) => {
	const [초대한사람, 초대받는사람] = users;
}
```

[destructuring](https://github.com/tipjs/javascript-style-guide#%EA%B5%AC%EC%A1%B0%ED%99%94%EB%8C%80%EC%9E%85destructuring)

2020-07-21 09:59 UTC, Junow commented on packages/server/src/services/chat.ts
> +    if (participantsList.length === 2) {
참여자가 2명 이라는 뜻은 어떤 의미인가요?

2020-07-21 09:59 UTC, Junow commented on packages/server/src/services/chat.ts
> +  let friendId
`myId, friendId` 가 이곳에서 선언된 이유가 따로 있을까요? 밑부분에 사용되는 `block scope` 내에서 선언한다면 이 변수가 어디에서 쓰이는지 한눈에 보일 것 같습니다.

2020-07-21 09:59 UTC, Junow commented on packages/server/src/services/chat.ts
> +  })
1개의 콜백함수 내에서 2개의 로직이 처리되고 있네요 테스트 어려운 코드일 뿐더러 에러발생시 발생지점을 탐색하기 어려울 수도 있습니다. 각 역할에 맞는 함수로 나눈다음 `method chaining` 으로 엮을 수 있을 것 같아요

```javascript
const findUser = () => {}
const makeRoomParticipants = () => {}
inviteUser
	.map(findUser)
	.forEach(makeRoomParticipants)
```

2020-07-21 09:59 UTC, Junow commented on packages/server/src/controllers/chat.ts
>  export const makeRoom = controllerHelper(async (req, res, next) => {
이 컨트롤러에서는 `if(inviteUser.length === 2)` 인경우에는 리턴값이 없고 그렇지 않은 경우에는 리턴값이 있네요 둘다 데이터를 리턴하던지 하지 않던지 통일이 필요해 보입니다. 다른 동작을 해야하는 경우는 다른 함수로 쪼개는게 저 적합하겠구요

2020-07-21 09:59 UTC, Junow commented on packages/server/package.json
> +    "pidusage": "^2.0.20",
`pidusage` 는 어떤 역할인가요?

2020-07-21 09:59 UTC, Junow commented on packages/client/src/system/Profile/index.tsx
> +  }, [])
의존성을 명시해주지 않았는데 `effect` 안에서 쓰이는 `login` 객체가 변경 되었다면 다시한번 `getProfile` 을 해봐야 하지 않을까요?

2020-07-21 15:36 UTC, brillante06 commented on packages/server/src/routes/v1/chat.route.ts
>  router.post('/:roomUuid', addMessage)
좋습니다 그렇게 수정해볼게요

2020-07-21 15:38 UTC, brillante06 commented on packages/server/src/services/chat.ts
> +  const friendUuid = user[0].uuid
좋은 방법이네요 수정해볼게요 물론 항상 자신이 가장 마지막에 들어오기 때문에 뒤바뀔일은 없습니다

2020-07-21 15:38 UTC, brillante06 commented on packages/server/src/services/chat.ts
> +    if (participantsList.length === 2) {
그룹채팅이 아닌 1대1대화를 의미합니다

2020-07-21 15:39 UTC, brillante06 commented on packages/server/src/services/chat.ts
> +  let friendId
이 부분은 아마 지워질 것 같습니다

2020-07-21 15:41 UTC, brillante06 commented on packages/server/package.json
> +    "pidusage": "^2.0.20",
자동 배포를 할때 pm2를 동작하기 위해 설치했었는데 아마 수동 배포에도 필요 할 것 같습니다

2020-07-21 15:41 UTC, brillante06 commented on packages/client/src/system/Profile/index.tsx
> +  }, [])
이 부분도 아마 수정될 것 같네요

2020-07-28 11:45 UTC, Junow requested changes

2020-07-28 11:45 UTC, Junow commented on packages/client/src/modules/room/action.ts
> +import { MockedComponentClass } from 'react-dom/test-utils'
얘는 어디다 쓰는거죠?

2020-07-28 11:45 UTC, Junow commented on packages/client/src/pages/main/ChatStart/index.tsx
> +  const friendList: SimpleUserType[] = useSelector((state: RootState) => state.friends)
여기 `SimpleUserType[]` 은 왜필요한 걸까요? `useSelector` 에서 뽑는 값에 따라 타입추론이 알아서 되는걸로 알고 있습니다. `friendList` 가 제대로된 타입 추론을 못한다면 `reducer` 에서 제대로된 타입들을 반환하는지 확인할 필요가 있습니다.

2020-07-28 11:45 UTC, Junow commented on packages/client/src/pages/main/ChatStart/index.tsx
> +      dispatch(getProfile())
요부분은 @bbumjun 이 리팩토링한 부분과 중복되겠네요

2020-07-28 11:45 UTC, Junow commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +          <ChatStart updateList={handleSelectedList}/>
`handleSelectedList` 은 `setSelectedList` 랑 동작이 같네요 굳이 다른 함수로 감쌀 필요는 없고 `setSelectedList` 만 넘겨도 되지 않을까요?

2020-07-28 11:45 UTC, Junow commented on packages/client/src/pages/main/ChatStart/index.tsx
> +    if (selectedUser.find((user) => user.uuid === uuid)) {
`uuid` 를 갖는 유저가 `selectedUser` 에 있는지 검사하는거죠? `Array.some` method 가 의미전달이 명확할 것 같습니다.

2020-07-28 11:45 UTC, Junow commented on packages/client/src/pages/main/ChatStart/index.tsx
> +        placeholder='초대할 상대를 입력해주세요'
jsx 리턴 부분이 들여쓰기가 안맞네요

2020-07-28 11:45 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +        throw httpError.IDK
적절한 error 를 만들어주세요

2020-07-28 11:45 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +  }
여기서 에러가 나는경우 방금 만들었던 `groupRoom` 은 삭제되어야 하지 않을까요? 방만들기랑 유저찾기를 트랜잭션으로 묶어서 처리하면 좋을 것 같습니다.

https://sequelize.org/master/manual/transactions.html

2020-07-28 11:45 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +  const user = await userService.findByUuid(inviteUser[inviteUser.length - 1].uuid)
`inviteUser[inviteUser.length - 1]` 의 무슨 데이터인가요? 맨뒤에 유저라는 게 어떤 사실을 나타내는지 알기가 힘듭니다.

2020-07-28 11:45 UTC, Junow commented on packages/server/src/services/chat.ts
> +    throw HttpError.IDK
적절한 에러를 만들어주세요

2020-07-30 08:41 UTC, brillante06 commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +          <ChatStart updateList={handleSelectedList}/>
setSelectedList 만 넘기면 제대로 동작을 하지 않아서 다른 함수로 감싸서 넘겨주었습니다.

2020-07-30 08:43 UTC, Junow commented on packages/client/src/components/NavigationBar/MakeChatTab/index.tsx
> +          <ChatStart updateList={handleSelectedList}/>
setter 를 하위로 넘겨서 처리하는걸 일반적인 패턴인데 동작하지 않는다는건 다른곳에 문제가 있다는 건가요?

2020-07-30 08:55 UTC, brillante06 commented on packages/server/src/controllers/chat.ts
> +  const user = await userService.findByUuid(inviteUser[inviteUser.length - 1].uuid)
마지막 유저는 항상 자기 자신이어서 저렇게 나타냈는데 어떻게 나타내면 좋을까요?

2020-07-30 12:21 UTC, Junow commented on packages/server/src/controllers/chat.ts
> +  const user = await userService.findByUuid(inviteUser[inviteUser.length - 1].uuid)
변수명을 적절히 바꾸거나 주석을 달거나 해줘야겠죠. 코드 가독성을 높이는 방법입니다.
그리고 요즘에는 주석을 많이 다는게 멋있지 않다고 생각하는 유행? 이 있는것 같아요

2020-07-30 13:17 UTC, Junow approved these changes

2020-07-30 13:18 UTC, merged