Feature/data caching
Lee-Park-Bae-Project/KAKIOTALK pull request #142
Opened 2020-07-24 18:13 UTC by bbumjun

`redux storage`의 데이터는 렌더링 될때마다 초기화되기 때문에, 지금까지는 페이지를 이동하거나 새로고침 할 때마다 매번 서버에 데이터를 다시 요청해야 했습니다.

이를 개선하기 위해서 `localStorage`에 데이터를 저장해 `caching`하는 방식을 구현하려고 했으나 `redux` 의 모든 `dispatch`마다 `localStorage`값을 변경하는 것은  DRY원칙에 어긋난다고 생각해 `redux-persist` 라이브러리를 사용해 `redux dispatch`만으로 `localStorage` 를 함께 관리하도록 하였습니다.

기존의 렌더링마다 서버에 데이터를 요청하는 대신, 구글 로그인을 성공하면 `redux storage`에 저장될 내프로필/친구목록/대화목록 을 서버에 한번 요청후 로그아웃 할 때 까지 새로 요청하지 않습니다.

로그아웃을 하게되면 `logoutAction`을 `dispatch`하는데, `Root reducer`에서 모든 `type`의 `state`를 초기화합니다.

---

- [905783b](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/905783bd6c65d7411bc3b48d1319d4c4c44541a9) 메인페이지 로딩 시 좌측 Navigation bar 노출되는 에러 해결
- [efec197](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/efec19795b0bab94099b9496c60a1ebfc9203f42) redux-persist 의존성 추가
- [16c8fb9](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/16c8fb9b0e818fe2f5041e24603afe087afe82af) modules/index 파일을 rootReducer & store 모듈로 분리 & App 에 persist store적용
- [96a0752](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/96a07522800d47a0fffa9fb2cd0581bb4bf0bb7a) 구글로그인 성공시 서버에 데이터 요청후 redux persist store에 저장
- [02a4f78](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/02a4f7830f09aa5416d6a8b4f225cc78cb7f67f4) 불필요해진 useAuth를 사용하는 로직은 일단 삭제했습니다

 현재 예상치못한 `bug`를 해결중에 있습니다.

- 친구 삭제 요청시에 서버는 요청을 잘 수행하지만 redux에서 해당 data가 삭제되지 않음

- root reducer에서 state를 초기화하는 로직에서 적절한 type을 사용하지 못함

2020-07-24 18:44 UTC, Junow commented
>기존의 렌더링마다 서버에 데이터를 요청하는 대신, 구글 로그인을 성공하면 redux storage에 저장될 내프로필/친구목록/대화목록 을 서버에 한번 요청후 로그아웃 할 때 까지 새로 요청하지 않습니다.

말씀하신거에 따르면 로그인 -> 친구추가 -> 새로고침 하면 새롭게 추가된 친구는 렌더링 안되지 않나요?

2020-07-25 03:14 UTC, bbumjun commented
> > 기존의 렌더링마다 서버에 데이터를 요청하는 대신, 구글 로그인을 성공하면 redux storage에 저장될 내프로필/친구목록/대화목록 을 서버에 한번 요청후 로그아웃 할 때 까지 새로 요청하지 않습니다.
> 
> 말씀하신거에 따르면 로그인 -> 친구추가 -> 새로고침 하면 새롭게 추가된 친구는 렌더링 안되지 않나요?

제 글에 약간의 오해의 소지가 있네요.. get관련 dispatch만 다시 요청하지 않는것이고, 친구추가/삭제 등의 dispatch는 실행하기 때문에 데이터베이스와 redux, localStorage도 함께 업데이트되면서 새로고침해도 추가된 친구가 함께 렌더링됩니다

2020-07-26 12:13 UTC, Junow requested changes

2020-07-26 12:13 UTC, Junow commented on packages/client/src/components/GoogleSignin/index.tsx
> +        dispatch(getRoomRequest())
`requset.getLogin` 을 실행을 saga에 넘겨서 성공했을때 4가지 액션을 디스패치 하는건 어떨까요? view 단에서 비동기 로직을 처리하다보면 비동기 로직이 끝나기 전에 component 가 unmaount 되면 에러가 발생하고 axios cancel 등 처리를 해줘야 할 것 같아요
https://www.robinwieruch.de/react-warning-cant-call-setstate-on-an-unmounted-component

2020-07-26 12:13 UTC, Junow commented on packages/client/src/modules/root-reducer.ts
> +import {
이 파일만 이름 컨벤션이 다르네요? rootReducer 로 통일할까요

2020-07-26 12:33 UTC, Junow commented on packages/client/src/modules/root-reducer.ts
> +import storage from 'redux-persist/lib/storage'
`localStorage`, `sessionStorage` 두개가 있는거 같은데 `localStorage` 를 선택하신 이유가 뭔가요?

2020-07-27 08:20 UTC, bbumjun commented on packages/client/src/modules/root-reducer.ts
> +import storage from 'redux-persist/lib/storage'
sessionStroage가 localStorage와는 다르게 같은 도메인이여도 탭 별로 개별적인 데이터 공간을 갖게되서, 흔한 경우는 아니지만 브라우저 탭을 여러개 열어서 kakiotalk을 실행해 어떤 작업을 수행할 경우에 sync가 맞지 않는 경우가 생길 수 있어서 localStorage를 선택했습니다.

2020-07-27 17:25 UTC, Junow commented on packages/client/src/modules/root-reducer.ts
> +import storage from 'redux-persist/lib/storage'
그렇다면 로그아웃 했을 때 `localStorage` 를 비우는 작업이 필요할 것 같은데 어떤 부분에서 처리하고 있나요?

`localStorage` 를 쓴다면 창을 닫고 나중에 다른 사람이 다시 접속 했을 때 그 정보가 남아있을 것 같은데 이 부분은 로그인할때 `자동로그인 허용` 등으로 허락을 받아놓으면 될까요?

2020-07-27 17:29 UTC, Junow requested changes

2020-07-27 17:29 UTC, Junow commented on packages/client/src/modules/sagas/loginSaga.ts
> +  yield takeEvery(LOGIN_REQUEST, loginRequestSaga)
`takeEvery` 보다 `takeLatest` 를 쓰는게 좋을 것 같아요

2020-07-27 17:29 UTC, Junow commented on packages/client/src/modules/sagas/loginSaga.ts
> +    alert.error(e.response.data.data.message)
로그인 실패했을때 여기로 에러가 던져지는거죠?

2020-07-27 18:27 UTC, Junow requested changes

2020-07-27 18:27 UTC, Junow commented on packages/client/src/modules/sagas/loginSaga.ts
> +    yield put(getRoomRequest())
위 4가지 `action` 은 묶어서 동시에 처리할수도 있을 것 같아요. 어쩌면 어플리케이션을 구동하는데 필수적인 데이터들이기 때문에 한 `action` 이라도 제대로 `dispatch` 되지 못했다면 에러를 캐치해서 다시 동작시켜야 할것 같기도합니다.

[saga 조합](https://mskims.github.io/redux-saga-in-korean/advanced/ComposingSagas.html) 을 이용하면 될것같기도 한데 예시가 `call` 로 되어있어서 `put` 을 동시에 처리할 수 있는지는 잘 모르곘네요 확인해보시면 좋을것 같습니다.

2020-07-28 07:54 UTC, bbumjun commented on packages/client/src/modules/root-reducer.ts
> +import storage from 'redux-persist/lib/storage'
rootReducer 파일 26 line에 `logoutAction`이 dispatch되었을 때 redux state를 초기화하도록 하고 있습니다.
- [https://www.digitalocean.com/community/tutorials/redux-reset-state-redux](https://www.digitalocean.com/community/tutorials/redux-reset-state-redux)
- [https://medium.com/@asher.cassetto.cohen/resetting-redux-state-with-a-root-reducer-bonus-how-to-reset-state-selectively-e2a008d0de61](https://medium.com/@asher.cassetto.cohen/resetting-redux-state-with-a-root-reducer-bonus-how-to-reset-state-selectively-e2a008d0de61)

말씀하신대로 직접 로그아웃하기 전까지 정보가 남아있기 때문에 자동로그인 여부를 유저라 선택할 수 있도록 하는게 좋은 방법일것 같네요. 😄

2020-07-28 07:55 UTC, bbumjun commented on packages/client/src/modules/sagas/loginSaga.ts
> +    alert.error(e.response.data.data.message)
넵

2020-07-28 07:58 UTC, bbumjun commented on packages/client/src/modules/sagas/loginSaga.ts
> +    yield put(getRoomRequest())
`yield all`을 사용하면 되겠군요!

2020-07-28 11:54 UTC, Junow commented on packages/client/src/modules/chat/action.ts
> +    amount } })
근데 코드가 왜이렇게 못생겨졌죠?;;

2020-07-28 12:40 UTC, bbumjun commented on packages/client/src/modules/chat/action.ts
> +    amount } })
흠;;; 전에 eslint에서 min-property를 2개에서 3개로 바꾼적이 있는데 그거때문인가요..

2020-07-30 13:52 UTC, Junow approved these changes

2020-07-30 13:52 UTC, merged