Dialog창 수정,1대1대화를 했을때 오류가 나지 않도록 해결
Lee-Park-Bae-Project/KAKIOTALK pull request #156
Opened 2020-08-04 10:12 UTC by brillante06

[1대1대화를 시작할때 방에 한명만 들어가는 문제 해결](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/089c82e71ed146cdc2387fe7eee6c93979c882d6)
1대1대화를 시작할때 서버에 친구 uuid와 이름만 전달을 했었는데 본인 아이디와 이름까지 전달하도록 수정

[대화창 만들 때 친구 목록이 많아도 Dialog 크기 일정하게 유지](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/45f82d64d8a8455830825816f299bf912177e097)
max-height를 40rem으로 고정시켜 친구 목록이 많아져도 일정 크기의 창을 유지하도록 수정

[처음 채팅 보낼때 null값의 metaInfo를 읽지 않도록 수정](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/commit/d9e40b676acf0e328327b097102586876ca14f97)
chatState의 길이가 0일때는 return 시켜 metaInfo를 읽지 않도록하고 chatArea의 useEffect에서 roomUuid나 chatState값이 변경될때 firstChat을 읽도록 수정

2020-08-04 14:06 UTC, Junow requested changes

2020-08-04 14:06 UTC, Junow commented on packages/client/src/common/constants.ts
> +const LOGIN_URL_PRODUCT = 'https://5f23d6929785a9000708d578--focused-mccarthy-3df3e2.netlify.app/login'
`https://kakiotalk.now.sh/login` 로 수정되었습니다.

2020-08-04 14:06 UTC, Junow commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
`chatState` 대신 `firstChat` 이 있어야하지 않을까요?

2020-08-04 14:06 UTC, Junow commented on packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
>    }, [chatState.data[roomUuid]])
`prevChats` 이 dependency 에 필요하지 않을까요?

2020-08-04 14:06 UTC, Junow commented on packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
> +    return null
null 을 리턴한 이유는 무엇인가요?

2020-08-04 14:06 UTC, Junow commented on packages/client/src/pages/chatroom/TextArea/TextArea.tsx
> +          ??
?? 의 의미는 뭔가요?

2020-08-04 14:06 UTC, Junow commented on packages/server/src/configs/index.ts
> +  ttl: process.env.NODE_ENV === 'development' ? '100h' : '2h' }
클라이언트랑 린트설정이 다른가요?

클라이언트쪽이랑 설정이 같다면 아래처럼 되야할 것 같습니다.
```typescript
export const jwtConfig = {
	secret: process.env.JWT_SECRET || 'secret',
	ttl: process.env.NODE_ENV === 'development' ? '100h' : '2h'
}
```

2020-08-04 17:08 UTC, brillante06 commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
아니용 firstChat으로 하면 방을 처음 만들고 채팅을 보냈을때 렌더링을 하지 못해요 chatState의 변화가 있을때 렌더링을 해주도록 해야 처음 보냈을때도 동작을 합니다

2020-08-04 17:09 UTC, brillante06 commented on packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
> +    return null
<Loading>을 하는 것보다는 아무것도 없는 편이 더 깔끔하다고 생각해요

2020-08-04 17:09 UTC, brillante06 commented on packages/client/src/pages/chatroom/TextArea/TextArea.tsx
> +          ??
죄송해요 전송이 맞습니다

2020-08-04 17:10 UTC, brillante06 commented on packages/server/src/configs/index.ts
> +  ttl: process.env.NODE_ENV === 'development' ? '100h' : '2h' }
다시 바꿨습니다

2020-08-05 13:29 UTC, Junow commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
그러면 if 문 안에 firstChat 이 있는 경우에 return 되는건 어떤 로직인가요?

2020-08-05 13:32 UTC, Junow commented on packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
> +    return null
prevChats 혹은 firstChat 없는 경우와 `chatState.isLoading === true` 인 경우가 서로 다른 UI 를 가진다는 건가요? 데이터가 준비되기 전에 아무것도 렌더링하고 싶지 않다는 건가요?

2020-08-05 13:38 UTC, brillante06 commented on packages/client/src/pages/chatroom/ChatArea/ChatList/ChatList.tsx
> +    return null
네 저희는 최대한 카카오톡과 비슷하게 하는 방향이기때문에 카카오톡도 처음 데이터를 가져올때는 아무것도 뜨지 않아서 같은 방향으로 가는게 좋을 것 같아요 chatState.isLoading === true인 경우도 수정해야겠네요

2020-08-05 14:36 UTC, brillante06 commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
chatState가 변경될때마다 getFirstChat을 할 수 없으니 처음 firstChat이 선언 된 이후에는 호출이 안되도록 하는게 괜찮겠죠?

2020-08-05 15:02 UTC, Junow commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
처음 한번만 요청 해야되는 데이터라면 dependency 를 비운 useEffect 를 사용해야 하지만 여기서는 roomUuid 가 data fetching 에 필요하기 때문에 dependency 에 roomUuid 가 필요하구요.

roomUuid 는 ChatArea 컴포넌트가 렌더링되는 동안에는 바뀔일이 없을 겁니다. 아마 roomUuid 가 바뀐다면 전체 페이지가reloading 되고 다른 방 데이터가 보이겠네요

작성하신 코드에서는 roomUuid, chatState 가 변경될때마다 effect 가 실행되는데 effect 안에서는 firstChat 을 요청하고 있고 이는 불필요한 effect 라고 할 수 있어요

말씀하신대로 chatState가 변경 될떄마다 getFirstChat 을 할 순 없지만 그 상황은 영준님이 dependency 에 chatState 를 넣어두셨기 때문이지 않나요?

하지만 위 코드의 effect 는 chatState 가 변경될때마다 실행될 필요가 없어보입니다.

2020-08-05 15:18 UTC, brillante06 commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
물론 chatState를 변경될때마다 effect가 실행되는건 불필요한 effect인건 알고 있습니다. 하지만 처음 채팅을 보냈을때 현재 설계된 로직에서는 더 좋은 방법이 떠오르지 않았습니다.

여러가지 생각을 해봤는데 처음 챗을 보냈을때 에러를 피하려면 저 방법 말고 다른 방법이 있는지 잘 모르겠네요.설계를 하신 준호님이 조금 더 나은 방법이 있다면 의견을 주세요. 저도 더 나은 방법이 있는지 더 찾아보겠습니다.

2020-08-05 15:53 UTC, bbumjun commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
제 생각도 `useEffect` 내부에 사용되지 않는 `chatState`를 dependency 로 넣어놓으면 당장 문제는 해결될 수도 있지만 불필요한  이펙트가 계속 실행될것 같습니다. 

방에 채팅이 하나도 없을때 `firstChat`이 `null`인 상황에서,  `TextArea`에서 첫 채팅을 칠 때 `firstChat`의  변화가 필요하니까 `firstChat` state를 `TextArea`와 `ChatArea`의 부모 컴포넌트인 `chatroom`의 `index.tsx`까지 끌어 올려서 `firstChat`의 `setter`를 `TextArea`에게 props로 넘겨주고 dependency에는 `roomUuid`와 `firstChat`만 넣는것이 어떨까 싶습니다.

2020-08-05 16:22 UTC, brillante06 commented on packages/client/src/pages/chatroom/ChatArea/ChatArea.tsx
> +  }, [roomUuid, chatState])
이것도 좋은 방법이네요 좀 더 효율적인 방법이 있는지 생각해봐야겠네요

2020-08-15 13:08 UTC, Junow approved these changes

2020-08-15 13:54 UTC, Junow commented
🚀 Stage Deployed on [here](https://kakiotalk.junow.vercel.app)

2020-08-15 14:01 UTC, merged