Feature/patch roomlist
Lee-Park-Bae-Project/KAKIOTALK pull request #159
Opened 2020-08-04 19:18 UTC by bbumjun

채팅목록 페이지에서 현재 열려있는 채팅방의 정보를 나타내는 `참여자 목록`, `참여자 수`, `마지막 메시지와 전송된 시간` , `안읽은 메시지 수`를 알맞게 패치하는 작업을 진행하고 있습니다.

- 1일 이상 경과했을 경우 `날짜`로, 그렇지 않을 경우 `시간`으로 전송시간 렌더링

- `Room` 모델과 `Chat` 모델을 `roomId`를 `foriegnKey`로  `hasMany`관계로 연결함(`Chat Model`에 `roomId` 추가)
- `Room service`의 `findAllRooms`에서 각 `room`에 `lastMessage`를 포함해 return 
- `Socket` 으로 새 메시지를 받으면 해당 채팅목록을 `update`하는 `action`, `reducer` 추가 

-----

- 안읽은 메시지 갯수 렌더링 구현 예정

2020-08-05 13:25 UTC, Junow commented
써놓은 모든작업 동시진행중인가요?

2020-08-05 15:04 UTC, Junow commented
혹시 redux 내에 `roomState` 변경사항 있습니까

2020-08-05 15:16 UTC, bbumjun commented
> 써놓은 모든작업 동시진행중인가요?

네엡.... 다음부턴 최대한 쪼개도록 하겠습니다.. 😭

2020-08-05 15:22 UTC, bbumjun commented
> @bbumjun
> 혹시 redux 내에 `roomState` 변경사항 있습니까



> @bbumjun
> 혹시 redux 내에 `roomState` 변경사항 있습니까

네 있습니다. `data[]` 에서  각 방마다 마지막 메시지인 `string type`의`lastMessage` 가 추가됐습니다

2020-08-05 15:44 UTC, Junow commented
> > 써놓은 모든작업 동시진행중인가요?
> 
> 네엡.... 다음부턴 최대한 쪼개도록 하겠습니다.. 😭

아녀.. 나눠서 하자구요

2020-08-10 05:28 UTC, Junow requested changes

2020-08-10 05:28 UTC, Junow commented on packages/client/src/modules/room/action.ts
> +export const getNewMessage = (roomUuid: string, content: string, updatedAt: string) => ({
`getNewMessage` 는 알림 용도인가요?

2020-08-10 06:03 UTC, bbumjun commented on packages/client/src/modules/room/action.ts
> +export const getNewMessage = (roomUuid: string, content: string, updatedAt: string) => ({
> `getNewMessage` 는 알림 용도인가요?

소켓을 통해서 받은 새 메시지로 채팅목록의 마지막 메시지, 업데이트 시간을 갱신하기 위한 액션입니다

2020-08-15 13:10 UTC, Junow commented
안읽은 메시지 개수는 이 pr 에서 떼고 머지하실건가요?

2020-08-17 04:55 UTC, bbumjun commented
> 안읽은 메시지 개수는 이 pr 에서 떼고 머지하실건가요?

그렇게 하려고 생각했는데, 생각해보니 안읽은 메시지 갯수를 아예 없애버리면 새 메시지가 온 채팅방과 그렇지 않은 채팅방이 너무 구분이 안되는 것 같아서 최소한 새 메시지가 와있다는 표시로 숫자대신 `new` 정도로 넣어주면 어떨까요?

2020-08-17 09:38 UTC, Junow commented
🚀 Stage Deployed on [here](https://kakiotalk.junow.vercel.app)

2020-08-17 09:46 UTC, Junow commented
🚀 Stage Deployed on [here](https://kakiotalk.junow.vercel.app)

2020-08-17 10:00 UTC, Junow approved these changes

2020-08-17 10:01 UTC, merged