Feature/socket
Lee-Park-Bae-Project/KAKIOTALK pull request #32
Opened 2020-04-30 17:41 UTC by bbumjun

2020-04-30 17:59 UTC, Junow requested changes

2020-04-30 17:59 UTC, Junow commented on client/package.json
> +    "react-cookie": "^4.0.3",
지금 상태에선 아마 필요없을거에여
서버에서 httpOnly 로 심어줘서

2020-04-30 17:59 UTC, Junow commented on client/src/App.tsx
> +import { CookiesProvider } from 'react-cookie';
지금 상태에선 아마 필요없을거에여

2020-04-30 17:59 UTC, Junow commented on client/src/common/request.ts
> +import { boolean } from '@storybook/addon-knobs';
안쓰이는 값같아요

2020-04-30 17:59 UTC, Junow commented on client/src/components/GoogleSignin/index.tsx
>  import dotenv from 'dotenv';
dotenv 는 common/constants.ts 에서 관리하도록하죠

2020-04-30 17:59 UTC, Junow commented on client/src/components/GoogleSignin/index.tsx
>    const history = useHistory();
useHistory 썼을떄랑 props 로 받을때랑 어떤 차이가 잇나여?

2020-04-30 17:59 UTC, Junow commented on client/src/containers/MainContainer.tsx
> +import Login from 'pages/login'
mainContainer 에서 Login 을 렌더링하지말고 /login 으로 리다이렉트해버리면 안될까요?

2020-04-30 17:59 UTC, Junow commented on client/src/modules/login/action.ts
> +export const loginRequest = (profile: any) => ({
profile: Profile 에서 profile:any 로 바꾼 이유가 있을까요?

2020-04-30 17:59 UTC, Junow commented on client/src/modules/login/reducer.ts
> +      return state.concat(isLogin);
이 코드를 이해하기로는 LOGIN_REQUEST 는 saga 쪽에서 받아야할것같은데 아닌가요?

2020-04-30 17:59 UTC, Junow commented on client/src/modules/sagas/loginSaga.ts
> +function* getLoginSaga({ payload }: any) {
타입을 Profile 로 지정하면 될거같아여

2020-04-30 17:59 UTC, Junow commented on client/src/types/index.ts
>  export interface Profile {
여기있는 Profile 타입이랑 User 타입은 통일이 필요할거같아요 같은 용도로 쓰일거같습니당

2020-04-30 17:59 UTC, Junow commented on server/src/routes/v1/user.route.ts
> +export default router;
린트가 안맞는 부분이 있나보네용

2020-04-30 18:02 UTC, bbumjun commented on client/package.json
> +    "react-cookie": "^4.0.3",
ok I got it

2020-04-30 18:02 UTC, bbumjun commented on client/src/App.tsx
> +import { CookiesProvider } from 'react-cookie';
okay sir

2020-04-30 18:08 UTC, bbumjun commented on client/src/modules/login/action.ts
> +export const loginRequest = (profile: any) => ({
앗 인터페이스에 명시된 타입이 다르길래 수정했는데 새로 pull한 코드에는 인터페이스가 올바르게 되어있네요 다시 수정할게여

2020-04-30 18:09 UTC, bbumjun commented on client/src/modules/login/reducer.ts
> +      return state.concat(isLogin);
@brillante06 님이 답장해주실겁니다

2020-05-01 04:34 UTC, brillante06 commented on client/src/modules/sagas/loginSaga.ts
> +function* getLoginSaga({ payload }: any) {
takeEvery에서 충돌이 나서 any로 해야합니다

2020-05-01 04:34 UTC, brillante06 commented on client/src/types/index.ts
>  export interface Profile {
왜 같은용도로 쓰이는거죠?? 로그인 정보랑 유저정보로 쓰이는거 아닌가용

2020-05-01 04:35 UTC, brillante06 commented on client/src/modules/login/reducer.ts
> +      return state.concat(isLogin);
로그인 정보를 받아서 로그인이 되었는지 유무를 사가로 넘겨주는데 어떻게 이해하신건가요?

2020-05-01 12:49 UTC, Junow commented on client/src/modules/login/reducer.ts
> +      return state.concat(isLogin);
LOGIN_REQUEST 액션은 [loginSaga](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/blob/feature%2Fsocket/client/src/modules/sagas/loginSaga.ts#L32) 에서 받아서 처리하고 있는데
그 다음에 [LOGIN_SUCCESS](https://github.com/Lee-Park-Bae-Project/KAKIOTALK/blob/feature%2Fsocket/client/src/modules/sagas/loginSaga.ts#L25) 액션이 디스패치 되면 reducer 에서 처리하는게 일반적이지 않나요?

2020-05-03 06:41 UTC, merged