Feature/login authorize
Lee-Park-Bae-Project/KAKIOTALK pull request #46
Opened 2020-05-06 01:13 UTC by brillante06

2020-05-06 11:35 UTC, Junow requested changes
수고링

2020-05-06 11:35 UTC, Junow commented on client/src/common/request.ts
>  const getUserInfo: AxiosRequestConfig = {
getLogout이 왜 post 인가요? 데이터보내거나 생성하지 않는것 같습니다

2020-05-06 11:35 UTC, Junow commented on client/package.json
> +    "@types/react-cookies": "^0.1.0",
react-cookies 라이브러리가 사용되지 않는것 같습니다. 지우는게 어떨까요

2020-05-06 11:35 UTC, Junow commented on client/src/components/NavigationBar/index.tsx
> +      <Logout onClick={logoutTabOnClick} />
Logout 컨포넌트는 로그인 하기 전에도 렌더링이 되나요? 어차피 로그인 화면으로 리다이렉트되니까 상관이 없을것 같기도 하구요.. 애매하네여

2020-05-06 11:35 UTC, Junow commented on server/src/configs/sequelize.js
> +    max: 1000,
이 값이 1000으로 늘어난 이유는 무엇인가요?

2020-05-06 11:35 UTC, Junow commented on server/src/controllers/auth.ts
> +    res.clearCookie(cookieName, { path: '/' });
path 값을 지정해야 동작하나요?

2020-05-06 11:35 UTC, Junow commented on server/src/controllers/auth.ts
> +    res.send('Success');
저희가 쓰고있는 response 함수를 이용해주세여
클라에서 response 를 받는 형식을 통일할 수 있습니다

2020-05-06 12:05 UTC, brillante06 commented on client/src/common/request.ts
>  const getUserInfo: AxiosRequestConfig = {
그러네요 수정할게용

2020-05-06 12:05 UTC, brillante06 commented on client/src/components/NavigationBar/index.tsx
> +      <Logout onClick={logoutTabOnClick} />
그 부분은 미륑때 토론하시져

2020-05-06 12:06 UTC, brillante06 commented on server/src/configs/sequelize.js
> +    max: 1000,
db가 안되서 수정하다가 늘어난것 같아요~

2020-05-06 12:06 UTC, brillante06 commented on server/src/controllers/auth.ts
> +    res.clearCookie(cookieName, { path: '/' });
안하면 서버에서만 지워집니다!

2020-05-07 13:11 UTC, Junow commented on server/src/configs/sequelize.js
> +    max: 1000,
다시 내려주세여 어디서보니까 pool 이 connection 을 미리 할당해 놓는거라고 들었는데 메모리 낭비가 아닐까여?

2020-05-07 13:12 UTC, Junow commented on server/src/controllers/auth.ts
> +    res.clearCookie(cookieName, { path: '/' });
서버에서만 지워진다는게 어떤 의미인가여?

2020-05-08 12:28 UTC, merged