Feature/delete friend
Lee-Park-Bae-Project/KAKIOTALK pull request #69
Opened 2020-05-15 15:22 UTC by bbumjun

- 친구 삭제기능 추가
- alert 관련 함수 swal으로 대체
- pop up 창 바깥 클릭시 창이 닫히도록 컴포넌트 수정

2020-05-15 15:42 UTC, Junow requested changes

2020-05-15 15:42 UTC, Junow commented on client/src/common/request.ts
> +})
restful 측면에서 볼때 delete method 는 어떠세요

2020-05-15 15:42 UTC, Junow commented on client/src/components/PopUp/index.tsx
> +  refs: any
혹시 명확한 타입아시면 추가 부탁합니다.

2020-05-15 15:42 UTC, Junow commented on client/src/modules/friends/reducer.ts
>        return newState;
바로 return 해도 되겠네요 newState 는 쓰이지 않으니까요

2020-05-15 15:42 UTC, Junow commented on client/src/modules/friends/reducer.ts
> +      swal('삭제되었습니다.',"","success")
alert 는 dispatch 실행한쪽에서 잡을 순 없나요? 아니면 request 객체 안에서요
요청하고 응답을 받을 쪽에서 처리할 수 있으면 좋겠습니다. 한눈에 사이클을 파악할 수 있으니까요

2020-05-15 15:42 UTC, Junow commented on client/src/modules/sagas/friendsSaga.ts
> +    const response = yield call(request.removeFriend,payload);
call 에 인자두개는 어떤 효과가있나요?

2020-05-15 15:42 UTC, Junow commented on client/src/pages/main/Friend/index.tsx
> +import swal from 'sweetalert'
swal 에 대한 의존성이 여기저기 퍼져 있는것 보단 util 함수로 만들 수 있을 것 같습니다.

2020-05-15 15:42 UTC, Junow commented on client/src/pages/main/index.tsx
> +  dialogRef: any,
타입 아시면 추가해주세요

2020-05-15 15:42 UTC, Junow commented on server/src/controllers/social.ts
>        await socialServce.addFriend(user.id, friend.id);
오타가 있네요 socialService

2020-05-15 15:42 UTC, Junow commented on server/src/controllers/social.ts
>      const data = await socialServce.getFriendsList(id);
id 나 data 가 없는 경우에 대한 에러처리가 필요해 보입니다.

2020-05-15 15:42 UTC, Junow commented on server/src/controllers/social.ts
> +    }
isAuth 미들웨어에서 로그인되지 않았을떄에 대한 예외처리가 되어 있지 않나요?

2020-05-15 15:42 UTC, Junow commented on server/src/controllers/social.ts
> +    const deleteUser = await userService.findByGoogleId(req.body.googleId);
user 나 deleteUser 가 없을때에 대한 예외처리가 필요해 보입니다.

2020-05-15 15:42 UTC, Junow commented on server/src/controllers/social.ts
> +    await socialServce.removeFriend(user.id,deleteUser.id)
removeFriend가 실패하는 경우는 없을까요?

2020-05-15 15:42 UTC, Junow commented on server/src/routes/v1/social.route.ts
> +router.post('/remove-friend',isAuth,removeFriend);
3개의 라우터 모두 isAuth 를 쓰고 있네요
맨앞에 router.all(isAuth) 인가 router.route(isAuth) 하면 모두 처리할 수 있습니다.

2020-05-15 15:42 UTC, Junow commented on server/src/services/socialService.ts
> +            attributes: ['googleId','email', 'name', 'status'],
유저에 대한 uuid 를 select 하지 않네요?
프론트에 유저 식별자를 제공하려면 필요하지 않나요?

2020-05-16 16:52 UTC, bbumjun commented on client/src/modules/sagas/friendsSaga.ts
> +    const response = yield call(request.removeFriend,payload);
두번째로 들어간 인자는 첫번째로 들어간 function의 인자로 들어갑니다.

2020-05-16 16:56 UTC, bbumjun commented on server/src/services/socialService.ts
> +            attributes: ['googleId','email', 'name', 'status'],
uuid대신 googleId를 식별자로 쓰고있었어요 수정하겟습니당

2020-05-17 08:35 UTC, merged