Feature/error fix
Lee-Park-Bae-Project/KAKIOTALK pull request #77
Opened 2020-05-21 10:15 UTC by bbumjun

- 지난 풀리퀘 리뷰에서 있었던 이슈 반영해 수정
- 타입 통일 후 생기는 충돌 해결
-  로그인 이전에 친구목록 요청하는 에러 수정

2020-05-21 19:26 UTC, Junow requested changes
@bbumjun 
> 채팅목록에 채팅이 하나도 없을때 채팅목록 대신 뭔가 띄워지면 좋을 것 같습니다!

로고 박아놓겠습니다

2020-05-21 19:26 UTC, Junow commented on client/src/common/request.ts
>    method:'POST',
method: delete 는 어떠세요 post 는 데이터 생성한다는 느낌이 개인적으로 있습니다

2020-05-21 19:26 UTC, Junow commented on client/src/components/Dialog/Dialog.stories.tsx
스토리북 업데이트 하시나요??

2020-05-21 19:26 UTC, Junow commented on client/src/modules/sagas/friendsSaga.ts
>  }
꼭해야되는건 아니지만 swal 로 안내문 표시하는것도 유틸함수로 존재하면 관리하기 편할 것 같아요

2020-05-21 19:26 UTC, Junow commented on client/src/pages/chatroom/index.tsx
> +  // const { id, name } = location.state;
필요없는 주석은 지워줍시당

2020-05-21 19:26 UTC, Junow commented on client/src/pages/main/Friend/index.tsx
>      }
클릭한 곳의 노드타입을 검사하는 건가요?

2020-05-21 19:26 UTC, Junow commented on client/src/common/utils.ts
> +export default swal
export 로 바꿔주세여

2020-05-21 19:26 UTC, Junow commented on client/src/pages/main/index.tsx
>    onPopupOutClicked:(e: React.MouseEvent<HTMLDivElement, MouseEvent>) => void;
메인 컴포넌트가 더 뚱뚱해졌네요 찢어야 겠습니다 대공사가 예상되네여;

2020-05-21 19:26 UTC, Junow commented on server/src/controllers/social.ts
> +    const user:IUser|null= await userService.findByGoogleId(googleId);
타입명시는 함수반환값 받는 곳 보다는 userService.findByGoogleId 에서 리턴타입에 대해서 정의해줘야 할 것 같아요

2020-05-21 19:26 UTC, Junow commented on server/src/controllers/social.ts
> +    }
에러에 대한 조건 하나면 걸면 코드 depth 가 깊어지지 않습니다. 여기서는 let data 같은 코드도 없어지고 const data = ... 형태로 바뀌겠네요
```typescript
if(!user){ 
  throw(createError(401,{message:'계정이 유효하지 않습니다.'}))
}
```

2020-05-21 19:26 UTC, Junow commented on server/src/controllers/social.ts
> +    const friend: IUser|null = await userService.findByEmail(friendEmail);
타입은 각 함수 리턴 타입에 명시해 줍시당

2020-05-21 19:26 UTC, Junow commented on server/src/controllers/social.ts
> +      throw(createError(401,{message:'유효하지 않은 계정입니다.'}))
비슷한 에러메시지가 반복되는걸 보니 유틸함수로 빼시죠 ㅋㅋㅋㅋㅋㅋ

2020-05-21 19:26 UTC, Junow commented on server/src/controllers/user.ts
> +import { IUser } from 'src/types'
이 코드 임포트 잘 되나요? src 로 시작하는거 안되서 ../../ 이러고 있습니다 ㅠ

2020-05-21 19:26 UTC, Junow commented on server/src/routes/v1/social.route.ts
> +router.use('',isAuth)
```typescript
router.use(isAuth)
```
로 해도 되더라구여

2020-05-21 19:26 UTC, Junow commented on server/src/routes/v1/social.route.ts
> +router.post('/delete-friend',deleteFriend);
데이터 삭제는 delete method

2020-05-23 08:54 UTC, bbumjun commented on client/src/components/Dialog/Dialog.stories.tsx
클라이언트-서버 인터페이스 타입을 통일하면서 스토리북의 변수들도 수정을 해야 에러가 없더라구요

2020-05-23 09:01 UTC, bbumjun commented on client/src/pages/main/Friend/index.tsx
>      }
네 검사하지 않으면 타입스크립트에서 에러를 검출하더라구요

2020-05-23 09:27 UTC, bbumjun commented on server/src/routes/v1/social.route.ts
> +router.use('',isAuth)
오홍 그렇군요

2020-05-23 20:37 UTC, Junow commented on client/src/components/Dialog/Dialog.stories.tsx
저도 그런경험 몇번 있었는데 관리 안하면 지워버리는게 낫겠네요 ㅠ

2020-05-24 05:17 UTC, bbumjun commented on server/src/controllers/user.ts
> +import { IUser } from 'src/types'
자동완성으로 임포트된 모듈이라 저도 몰랏는데 잘 동작하는것 같아요 ㅋㅋㅋ

2020-05-24 09:07 UTC, Junow requested changes

2020-05-24 09:07 UTC, Junow commented on server/src/common/utils.ts
> + }
멋잇네여 👍

2020-05-24 09:07 UTC, Junow commented on server/src/models/user.ts
> +import {FriendModel } from './friends'
userModel 과 friendModel 이 다른점이 있나요? 관계땜에 만들어진 모델인가요?

2020-05-24 09:24 UTC, bbumjun commented on server/src/models/user.ts
> +import {FriendModel } from './friends'
네 roomParticipants처럼 관계 때문에 만들어진 모델이에요
user-friend-user로 연결되어있는데 interface에 명시가 안되있어서 추가했습니다

2020-05-24 09:28 UTC, Junow commented on server/src/models/user.ts
> +import {FriendModel } from './friends'
가상 모델인가요? 실제 디비에 테이블은 필요없죠?

2020-05-24 09:32 UTC, bbumjun commented on server/src/models/user.ts
> +import {FriendModel } from './friends'
실제로 디비에 테이블로 들어있습니다

2020-05-24 09:36 UTC, Junow commented on server/src/models/user.ts
> +import {FriendModel } from './friends'
migration 은 새로 생성이 안되어있네요?

2020-05-24 09:36 UTC, bbumjun commented on server/src/models/user.ts
> +import {FriendModel } from './friends'
필요하지 않을까요??

2020-05-24 12:33 UTC, Junow approved these changes

2020-05-24 12:34 UTC, merged